name = "rumbo-api"
main = "src/worker.ts"
compatibility_date = "2025-01-01"

[vars]
ENVIRONMENT = "production"
CORS_ORIGINS = "https://rumbo.pages.dev"

[env.staging]
name = "rumbo-api-staging"
[env.staging.vars]
ENVIRONMENT = "staging"
CORS_ORIGINS = "https://staging.rumbo.pages.dev"
